#!/bin/bash

if [[ $FORCE_USE_NVM == 'true' ]]; then
    echo "(running script using node via nvm)"

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
fi

# arb1
yarn fullList --l2NetworkID 42161
yarn arbify --l2NetworkID 42161 --tokenList https://gateway.ipfs.io/ipns/tokens.uniswap.org
yarn arbify --l2NetworkID 42161 --tokenList https://www.gemini.com/uniswap/manifest.json
yarn arbify --l2NetworkID 42161 --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json

# nova
# yarn fullList --l2NetworkID 42170
yarn arbify --l2NetworkID 42170 --tokenList https://gateway.ipfs.io/ipns/tokens.uniswap.org
yarn arbify --l2NetworkID 42170 --tokenList https://www.gemini.com/uniswap/manifest.json
yarn arbify --l2NetworkID 42170 --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json

# goerli rollup testnet
yarn arbify --l2NetworkID 421613 --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json
yarn fullList --l2NetworkID 421613
