#!/bin/bash

yarn fullList
yarn arbify --tokenList https://gateway.ipfs.io/ipns/tokens.uniswap.org
yarn arbify --tokenList https://www.gemini.com/uniswap/manifest.json
yarn arbify --tokenList https://api.coinmarketcap.com/data-api/v3/uniswap/all.json